"""
algo.py - Fractal Edge Strategy
Consumes 'Fractal Delta Bars' generated by build_bars.py.
"""
import sys

# NO complex calculations here. 
# Math was done in C/Rust speeds during build.

def decide(bar):
    """
    Input: Tuple (ts_start, ts_end, o, h, l, c, vol, delta, eff, impact)
    Output: Signal (-1, 0, 1)
    """
    ts_start, ts_end, o, h, l, c, vol, delta, eff, impact = bar
    
    # --- LOGIC: The "Absorption Hunter" ---
    
    # 1. Define Regime
    # High Efficiency (> 0.6) = Trending / Momentum
    # Low Efficiency (< 0.3) = Choppy / Mean Reversion / Absorption
    
    signal = 0
    
    if eff > 0.6:
        # MOMENTUM REGIME
        # If Delta agrees with Price Direction, Follow it.
        # But check Impact: We want HIGH impact (price moving easily)
        
        price_move = c - o
        
        if delta > 0 and price_move > 0:
            # Bullish Flow + Bullish Price + Efficient Path
            signal = 1
        elif delta < 0 and price_move < 0:
            signal = -1
            
    elif eff < 0.25:
        # ABSORPTION REGIME (The "Edge")
        # Heavy Delta but Price NOT moving efficiently (Grinding)
        # This often signals a reversal or iceberg absorption.
        
        # If Huge Buying (Delta > 0) but Price NOT going up efficiently
        # -> Sellers are absorbing. FADE IT.
        if delta > 0:
            signal = -1 # Sell into the absorption
            
        # If Huge Selling (Delta < 0) but Price holding
        # -> Buyers are absorbing. BUY IT.
        elif delta < 0:
            signal = 1
            
    return signal